name: build

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
